# Cloud Build config to build and push image to Artifact Registry
# Usage example:
# gcloud builds submit \
#   --substitutions=_REGION=us-central1,_REPOSITORY=web,_IMAGE=mentoriumai-landing,_TAG=latest \
#   --project=$PROJECT_ID

substitutions:
  # Region of your Artifact Registry repository (e.g., us-central1)
  _REGION: us-central1
  # Name of the Artifact Registry repository (e.g., web)
  _REPOSITORY: web
  # Image name within the repository (e.g., mentoriumai-landing)
  _IMAGE: mentoriumai-landing
  # Image tag (e.g., latest, commit SHA, or release semver)
  _TAG: latest

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${_TAG}

steps:
  - id: "Build image"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${_TAG}"
      - "."

  - id: "Push image"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${_TAG}"

# Notes:
# - Ensure the Artifact Registry repo exists:
#   gcloud artifacts repositories create ${_REPOSITORY} \
#     --repository-format=docker \
#     --location=${_REGION}
# - Make sure the Cloud Build service account has roles to push to Artifact Registry:
#   roles/artifactregistry.writer
# - Trigger build:
#   gcloud builds submit --project $PROJECT_ID \
#     --substitutions=_REGION=us-central1,_REPOSITORY=web,_IMAGE=mentoriumai-landing,_TAG=$(git rev-parse --short HEAD)
